### ISSUE TITLE
Not sure how to destroy/end 

### ISSUE THREAD

**Issue by Fever905** [adolfintel/warpspeed#5]
hey,

I'm running a single page app and trying to use the warpspeed for my endin screen.  I get it to load up no problem using :

var ai_background = new WarpSpeed("bkFrame",{"speed":2,"speedAdjFactor":0.06,"density":1.7,"shape":"square","warpEffect":true,"warpEffectLength":5,"depthFade":false,"starSize":3,"backgroundColor":"hsl(263,45%,7%)","starColor":"#FFFFFF"});

How do I close/destroy the instance?

**Comment by adolfintel** [comment]
Just call `ai_background.destroy()`
